# 4.	How have teams changed in how often they shoot 3-pointers (FG3A) and how accurate they are (FG3_PCT) between 2010-2024?
#     a.	Get top 10 teams(or all teams and use a splicer in powerbi to select temas) (or look at the overall average and compare teams to that average to see where they land) and look at the average or median and show its improvement or decline over the timeframe of the data. Also include the fg%.Look at overall average over the timespan and compare the total overall and compare the overall teams average to that. (Stretch question: does higher 3pt% lead to more wins year over year)

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
#read in data
regular_season_totals = pd.read_csv('../NBA_Player_Evolution_2020-2024/regular_season_totals_2010_2024.csv')

#Change season_year and game_date to date-time format
regular_season_totals['GAME_DATE'] = pd.to_datetime(regular_season_totals['GAME_DATE'])

regular_season_totals['SEASON_YEAR'].unique()

array(['2022-23', '2020-21', '2013-14', '2018-19', '2012-13', '2017-18',
       '2019-20', '2014-15', '2023-24', '2015-16', '2021-22', '2010-11',
       '2016-17', '2011-12'], dtype=object)

In [36]:
#Filter necessary rows
regular_season_totals = regular_season_totals[['SEASON_YEAR', 'GAME_DATE', 'GAME_ID', 'TEAM_ID', 'TEAM_NAME', 'WL', 'FG3A', 'FG3_PCT', 'FG_PCT']]

In [346]:
#Filter year over year
year_2010_11 = regular_season_totals[regular_season_totals['SEASON_YEAR']=='2010-11']

#Find the overall 3p% per team for this year
team_2010_11_avg_pct = year_2010_11.groupby('TEAM_NAME')['FG3_PCT'].mean().reset_index()

#Find the average 3 points attempted by team
team_2010_11_avg_fga = year_2010_11.groupby('TEAM_NAME')['FG3A'].mean().reset_index()

#Find the years average FG3A 
year_2010_11_avg_fga = year_2010_11['FG3A'].mean()

#Find the years average FG3%
year_2010_11_avg_3perc = year_2010_11['FG3_PCT'].mean()

#Filter the DF to just show wins
wins_2010_11 = year_2010_11[year_2010_11['WL'] == 'W']

#Find the teams overall wins
year_2010_11_total_wins = wins_2010_11.groupby('TEAM_NAME')['WL'].count().reset_index(name='Total_Wins')

In [450]:
team_2010_11_avg_pct['FG3A']= team_2010_11_avg_fga['FG3A']
team_2010_11_avg_pct['SEASON_YEAR'] = '2010-2011'
team_2010_11_avg_pct['Total_Wins']= year_2010_11_total_wins['Total_Wins']
team_2010_11_avg_pct

                 TEAM_NAME   FG3_PCT       FG3A SEASON_YEAR  Total_Wins
0            Atlanta Hawks  0.359488  17.402439   2010-2011          44
1           Boston Celtics  0.361451  13.646341   2010-2011          56
2        Charlotte Bobcats  0.319585  14.670732   2010-2011          34
3            Chicago Bulls  0.360329  17.256098   2010-2011          62
4      Cleveland Cavaliers  0.341341  18.158537   2010-2011          19
5         Dallas Mavericks  0.364427  21.560976   2010-2011          57
6           Denver Nuggets  0.379817  20.780488   2010-2011          50
7          Detroit Pistons  0.370073  15.317073   2010-2011          30
8    Golden State Warriors  0.384293  21.329268   2010-2011          36
9          Houston Rockets  0.366317  22.475610   2010-2011          43
10          Indiana Pacers  0.349854  20.158537   2010-2011          37
11    Los Angeles Clippers  0.337427  18.524390   2010-2011          32
12      Los Angeles Lakers  0.351561  18.134146   2010-2011          57
13       Memphis Grizzlies  0.328683  11.292683   2010-2011          46
14              Miami Heat  0.367354  18.036585   2010-2011          58
15         Milwaukee Bucks  0.341780  17.243902   2010-2011          35
16  Minnesota Timberwolves  0.374915  19.085366   2010-2011          17
17         New Jersey Nets  0.344720  16.304878   2010-2011          24
18     New Orleans Hornets  0.362463  15.024390   2010-2011          46
19         New York Knicks  0.365524  25.378049   2010-2011          42
20   Oklahoma City Thunder  0.349293  17.109756   2010-2011          55
21           Orlando Magic  0.361305  25.646341   2010-2011          52
22      Philadelphia 76ers  0.351939  15.219512   2010-2011          41
23            Phoenix Suns  0.369268  22.646341   2010-2011          40
24  Portland Trail Blazers  0.345720  18.329268   2010-2011          48
25        Sacramento Kings  0.335232  15.573171   2010-2011          24
26       San Antonio Spurs  0.395585  21.060976   2010-2011          61
27         Toronto Raptors  0.308415  13.304878   2010-2011          22
28               Utah Jazz  0.334207  15.317073   2010-2011          39
29      Washington Wizards  0.326415  14.414634   2010-2011          23

In [416]:
#finished dataframe for 2010-2011
team_2010_11_avg_pct

                 TEAM_NAME   FG3_PCT       FG3A SEASON_YEAR  Total_Wins
0            Atlanta Hawks  0.359488  17.402439   2010-2011          44
1           Boston Celtics  0.361451  13.646341   2010-2011          56
2        Charlotte Bobcats  0.319585  14.670732   2010-2011          34
3            Chicago Bulls  0.360329  17.256098   2010-2011          62
4      Cleveland Cavaliers  0.341341  18.158537   2010-2011          19
5         Dallas Mavericks  0.364427  21.560976   2010-2011          57
6           Denver Nuggets  0.379817  20.780488   2010-2011          50
7          Detroit Pistons  0.370073  15.317073   2010-2011          30
8    Golden State Warriors  0.384293  21.329268   2010-2011          36
9          Houston Rockets  0.366317  22.475610   2010-2011          43
10          Indiana Pacers  0.349854  20.158537   2010-2011          37
11    Los Angeles Clippers  0.337427  18.524390   2010-2011          32
12      Los Angeles Lakers  0.351561  18.134146   2010-2011          57
13       Memphis Grizzlies  0.328683  11.292683   2010-2011          46
14              Miami Heat  0.367354  18.036585   2010-2011          58
15         Milwaukee Bucks  0.341780  17.243902   2010-2011          35
16  Minnesota Timberwolves  0.374915  19.085366   2010-2011          17
17         New Jersey Nets  0.344720  16.304878   2010-2011          24
18     New Orleans Hornets  0.362463  15.024390   2010-2011          46
19         New York Knicks  0.365524  25.378049   2010-2011          42
20   Oklahoma City Thunder  0.349293  17.109756   2010-2011          55
21           Orlando Magic  0.361305  25.646341   2010-2011          52
22      Philadelphia 76ers  0.351939  15.219512   2010-2011          41
23            Phoenix Suns  0.369268  22.646341   2010-2011          40
24  Portland Trail Blazers  0.345720  18.329268   2010-2011          48
25        Sacramento Kings  0.335232  15.573171   2010-2011          24
26       San Antonio Spurs  0.395585  21.060976   2010-2011          61
27         Toronto Raptors  0.308415  13.304878   2010-2011          22
28               Utah Jazz  0.334207  15.317073   2010-2011          39
29      Washington Wizards  0.326415  14.414634   2010-2011          23

In [418]:
#Filter year over year
year_2011_12 = regular_season_totals[regular_season_totals['SEASON_YEAR']=='2011-12']

#Find the overall 3p% per team for this year
team_2011_12_avg_pct = year_2011_12.groupby('TEAM_NAME')['FG3_PCT'].mean().reset_index()

#Find the average 3 points attempted by team
team_2011_12_avg_fga = year_2011_12.groupby('TEAM_NAME')['FG3A'].mean().reset_index()

#Find the years average FG3A 
year_2011_12_avg_fga = year_2011_12['FG3A'].mean()

#Find the years average FG3%
year_2011_12_avg_3perc = year_2011_12['FG3_PCT'].mean()

#Filter the DF to just show wins
wins_2011_12 = year_2011_12[year_2011_12['WL'] == 'W']

#Find the teams overall wins
year_2011_12_total_wins = wins_2011_12.groupby('TEAM_NAME')['WL'].count().reset_index(name='Total_Wins')

In [448]:
team_2011_12_avg_pct['FG3A']= team_2011_12_avg_fga['FG3A']
team_2011_12_avg_pct['SEASON_YEAR'] = '2011-2012'
team_2011_12_avg_pct['Total_Wins']= year_2011_12_total_wins['Total_Wins']
team_2011_12_avg_pct

                 TEAM_NAME   FG3_PCT       FG3A SEASON_YEAR  Total_Wins
0            Atlanta Hawks  0.371727  20.151515   2011-2012          40
1           Boston Celtics  0.361061  14.969697   2011-2012          39
2        Charlotte Bobcats  0.287742  13.515152   2011-2012           7
3            Chicago Bulls  0.375848  16.924242   2011-2012          50
4      Cleveland Cavaliers  0.343970  19.287879   2011-2012          21
5         Dallas Mavericks  0.340591  22.181818   2011-2012          36
6           Denver Nuggets  0.334818  19.863636   2011-2012          38
7          Detroit Pistons  0.334697  13.878788   2011-2012          25
8    Golden State Warriors  0.379848  20.469697   2011-2012          23
9          Houston Rockets  0.361000  20.151515   2011-2012          34
10          Indiana Pacers  0.367015  16.121212   2011-2012          42
11    Los Angeles Clippers  0.351924  21.833333   2011-2012          40
12      Los Angeles Lakers  0.322515  16.848485   2011-2012          41
13       Memphis Grizzlies  0.323030  12.863636   2011-2012          41
14              Miami Heat  0.352485  15.606061   2011-2012          46
15         Milwaukee Bucks  0.339152  19.166667   2011-2012          31
16  Minnesota Timberwolves  0.329000  21.560606   2011-2012          26
17         New Jersey Nets  0.335136  22.439394   2011-2012          22
18     New Orleans Hornets  0.336273  11.772727   2011-2012          21
19         New York Knicks  0.328515  23.303030   2011-2012          36
20   Oklahoma City Thunder  0.362515  19.954545   2011-2012          47
21           Orlando Magic  0.373667  27.045455   2011-2012          37
22      Philadelphia 76ers  0.353061  14.590909   2011-2012          35
23            Phoenix Suns  0.342955  19.621212   2011-2012          33
24  Portland Trail Blazers  0.342833  20.939394   2011-2012          28
25        Sacramento Kings  0.311667  19.712121   2011-2012          22
26       San Antonio Spurs  0.396288  21.287879   2011-2012          50
27         Toronto Raptors  0.332061  16.287879   2011-2012          23
28               Utah Jazz  0.317924  12.803030   2011-2012          36
29      Washington Wizards  0.310939  16.287879   2011-2012          20

In [144]:
#Filter year over year
year_2012_13 = regular_season_totals[regular_season_totals['SEASON_YEAR']=='2012-13']

#Find the overall 3p% per team for this year
team_2012_13_avg_pct = year_2012_13.groupby('TEAM_NAME')['FG3_PCT'].mean().reset_index()

#Find the average 3 points attempted by team
team_2012_13_avg_fga = year_2012_13.groupby('TEAM_NAME')['FG3A'].mean().reset_index()

#Find the years average FG3A 
year_2012_13_avg_fga = year_2012_13['FG3A'].mean()

#Find the years average FG3%
year_2012_13_avg_3perc = year_2012_13['FG3_PCT'].mean()

#Filter the DF to just show wins
wins_2012_13 = year_2012_13[year_2012_13['WL'] == 'W']

#Find the teams overall wins
year_2012_13_total_wins = wins_2012_13.groupby('TEAM_NAME')['WL'].count().reset_index(name='Total_Wins')

In [422]:
team_2012_13_avg_pct['FG3A']= team_2012_13_avg_fga['FG3A']
team_2012_13_avg_pct['SEASON_YEAR'] = '2012-2013'
team_2012_13_avg_pct['Total_Wins']= year_2012_13_total_wins['Total_Wins']
team_2012_13_avg_pct

                 TEAM_NAME   FG3_PCT       FG3A SEASON_YEAR  Total_Wins
0            Atlanta Hawks  0.373317  23.182927   2012-2013          44
1           Boston Celtics  0.360049  17.160494   2012-2013          41
2            Brooklyn Nets  0.356366  21.463415   2012-2013          49
3        Charlotte Bobcats  0.333854  17.060976   2012-2013          21
4            Chicago Bulls  0.350817  15.426829   2012-2013          45
5      Cleveland Cavaliers  0.344024  19.280488   2012-2013          24
6         Dallas Mavericks  0.366098  19.853659   2012-2013          41
7           Denver Nuggets  0.342122  18.512195   2012-2013          57
8          Detroit Pistons  0.353427  17.560976   2012-2013          29
9    Golden State Warriors  0.400110  19.902439   2012-2013          47
10         Houston Rockets  0.365817  28.890244   2012-2013          45
11          Indiana Pacers  0.349235  19.740741   2012-2013          49
12    Los Angeles Clippers  0.354378  21.365854   2012-2013          56
13      Los Angeles Lakers  0.353439  24.573171   2012-2013          45
14       Memphis Grizzlies  0.340976  13.500000   2012-2013          56
15              Miami Heat  0.393561  22.060976   2012-2013          66
16         Milwaukee Bucks  0.355756  20.365854   2012-2013          38
17  Minnesota Timberwolves  0.300610  17.987805   2012-2013          31
18     New Orleans Hornets  0.358341  17.975610   2012-2013          27
19         New York Knicks  0.373207  28.914634   2012-2013          54
20   Oklahoma City Thunder  0.376573  19.365854   2012-2013          60
21           Orlando Magic  0.322415  18.743902   2012-2013          20
22      Philadelphia 76ers  0.358561  17.536585   2012-2013          34
23            Phoenix Suns  0.328317  17.743902   2012-2013          25
24  Portland Trail Blazers  0.351390  23.219512   2012-2013          33
25        Sacramento Kings  0.358049  20.500000   2012-2013          28
26       San Antonio Spurs  0.377207  21.512195   2012-2013          58
27         Toronto Raptors  0.336549  20.304878   2012-2013          34
28               Utah Jazz  0.358171  16.890244   2012-2013          43
29      Washington Wizards  0.366476  18.231707   2012-2013          29

In [142]:
#Filter year over year
year_2013_14 = regular_season_totals[regular_season_totals['SEASON_YEAR']=='2013-14']

#Find the overall 3p% per team for this year
team_2013_14_avg_pct = year_2013_14.groupby('TEAM_NAME')['FG3_PCT'].mean().reset_index()

#Find the average 3 points attempted by team
team_2013_14_avg_fga = year_2013_14.groupby('TEAM_NAME')['FG3A'].mean().reset_index()

#Find the years average FG3A 
year_2013_14_avg_fga = year_2013_14['FG3A'].mean()

#Find the years average FG3%
year_2013_14_avg_3perc = year_2013_14['FG3_PCT'].mean()

#Filter the DF to just show wins
wins_2013_14 = year_2013_14[year_2013_14['WL'] == 'W']

#Find the teams overall wins
year_2013_14_total_wins = wins_2013_14.groupby('TEAM_NAME')['WL'].count().reset_index(name='Total_Wins')

In [424]:
team_2013_14_avg_pct['FG3A']= team_2013_14_avg_fga['FG3A']
team_2013_14_avg_pct['SEASON_YEAR'] = '2013-2014'
team_2013_14_avg_pct['Total_Wins']= year_2013_14_total_wins['Total_Wins']
team_2013_14_avg_pct

                 TEAM_NAME   FG3_PCT       FG3A SEASON_YEAR  Total_Wins
0            Atlanta Hawks  0.359793  25.804878   2013-2014          38
1           Boston Celtics  0.327171  21.085366   2013-2014          25
2            Brooklyn Nets  0.361634  23.439024   2013-2014          44
3        Charlotte Bobcats  0.349585  17.939024   2013-2014          43
4            Chicago Bulls  0.346598  17.792683   2013-2014          48
5      Cleveland Cavaliers  0.354768  20.000000   2013-2014          33
6         Dallas Mavericks  0.381805  22.890244   2013-2014          49
7           Denver Nuggets  0.357195  23.890244   2013-2014          36
8          Detroit Pistons  0.312463  19.268293   2013-2014          29
9    Golden State Warriors  0.379049  24.841463   2013-2014          51
10         Houston Rockets  0.356598  26.573171   2013-2014          54
11          Indiana Pacers  0.356317  18.804878   2013-2014          56
12    Los Angeles Clippers  0.351256  23.975610   2013-2014          57
13      Los Angeles Lakers  0.377073  24.780488   2013-2014          27
14       Memphis Grizzlies  0.351915  13.987805   2013-2014          50
15              Miami Heat  0.364159  22.304878   2013-2014          54
16         Milwaukee Bucks  0.356524  18.939024   2013-2014          15
17  Minnesota Timberwolves  0.338220  21.426829   2013-2014          40
18    New Orleans Pelicans  0.372500  15.890244   2013-2014          34
19         New York Knicks  0.368939  24.853659   2013-2014          37
20   Oklahoma City Thunder  0.364439  22.426829   2013-2014          59
21           Orlando Magic  0.353659  19.463415   2013-2014          23
22      Philadelphia 76ers  0.312695  22.524390   2013-2014          19
23            Phoenix Suns  0.375585  25.060976   2013-2014          48
24  Portland Trail Blazers  0.370659  25.256098   2013-2014          54
25        Sacramento Kings  0.328207  17.987805   2013-2014          28
26       San Antonio Spurs  0.397098  21.426829   2013-2014          62
27         Toronto Raptors  0.370317  23.378049   2013-2014          48
28               Utah Jazz  0.344073  19.231707   2013-2014          25
29      Washington Wizards  0.376500  20.780488   2013-2014          44

In [140]:
#Filter year over year
year_2014_15 = regular_season_totals[regular_season_totals['SEASON_YEAR']=='2014-15']

#Find the overall 3p% per team for this year
team_2014_15_avg_pct = year_2014_15.groupby('TEAM_NAME')['FG3_PCT'].mean().reset_index()

#Find the average 3 points attempted by team
team_2014_15_avg_fga = year_2014_15.groupby('TEAM_NAME')['FG3A'].mean().reset_index()

#Find the years average FG3A 
year_2014_15_avg_fga = year_2014_15['FG3A'].mean()

#Find the years average FG3%
year_2014_15_avg_3perc = year_2014_15['FG3_PCT'].mean()

#Filter the DF to just show wins
wins_2014_15 = year_2014_15[year_2014_15['WL'] == 'W']

#Find the teams overall wins
year_2014_15_total_wins = wins_2014_15.groupby('TEAM_NAME')['WL'].count().reset_index(name='Total_Wins')

In [426]:
team_2014_15_avg_pct['FG3A']= team_2014_15_avg_fga['FG3A']
team_2014_15_avg_pct['SEASON_YEAR'] = '2014-2015'
team_2014_15_avg_pct['Total_Wins']= year_2014_15_total_wins['Total_Wins']
team_2014_15_avg_pct

                 TEAM_NAME   FG3_PCT       FG3A SEASON_YEAR  Total_Wins
0            Atlanta Hawks  0.380146  26.243902   2014-2015          60
1           Boston Celtics  0.326183  24.646341   2014-2015          40
2            Brooklyn Nets  0.327195  19.914634   2014-2015          38
3        Charlotte Hornets  0.312976  19.097561   2014-2015          33
4            Chicago Bulls  0.353585  22.256098   2014-2015          50
5      Cleveland Cavaliers  0.363756  27.475610   2014-2015          53
6         Dallas Mavericks  0.349037  25.390244   2014-2015          50
7           Denver Nuggets  0.327024  24.780488   2014-2015          30
8          Detroit Pistons  0.339622  24.914634   2014-2015          32
9    Golden State Warriors  0.397878  27.036585   2014-2015          67
10         Houston Rockets  0.348476  32.682927   2014-2015          56
11          Indiana Pacers  0.352134  21.219512   2014-2015          38
12    Los Angeles Clippers  0.372476  26.853659   2014-2015          56
13      Los Angeles Lakers  0.340280  18.853659   2014-2015          21
14       Memphis Grizzlies  0.336305  15.195122   2014-2015          55
15              Miami Heat  0.335854  20.231707   2014-2015          37
16         Milwaukee Bucks  0.363829  18.292683   2014-2015          41
17  Minnesota Timberwolves  0.325220  14.914634   2014-2015          16
18    New Orleans Pelicans  0.371500  19.304878   2014-2015          45
19         New York Knicks  0.353268  19.682927   2014-2015          17
20   Oklahoma City Thunder  0.335646  22.731707   2014-2015          45
21           Orlando Magic  0.347866  19.487805   2014-2015          25
22      Philadelphia 76ers  0.314988  26.341463   2014-2015          18
23            Phoenix Suns  0.337598  24.975610   2014-2015          39
24  Portland Trail Blazers  0.361171  27.207317   2014-2015          51
25        Sacramento Kings  0.339805  16.463415   2014-2015          29
26       San Antonio Spurs  0.361805  22.524390   2014-2015          55
27         Toronto Raptors  0.351171  25.121951   2014-2015          49
28               Utah Jazz  0.344085  21.719512   2014-2015          38
29      Washington Wizards  0.361732  16.841463   2014-2015          46

In [138]:
#Filter year over year
year_2015_16 = regular_season_totals[regular_season_totals['SEASON_YEAR']=='2015-16']

#Find the overall 3p% per team for this year
team_2015_16_avg_pct = year_2015_16.groupby('TEAM_NAME')['FG3_PCT'].mean().reset_index()

#Find the average 3 points attempted by team
team_2015_16_avg_fga = year_2015_16.groupby('TEAM_NAME')['FG3A'].mean().reset_index()

#Find the years average FG3A 
year_2015_16_avg_fga = year_2015_16['FG3A'].mean()

#Find the years average FG3%
year_2015_16_avg_3perc = year_2015_16['FG3_PCT'].mean()

#Filter the DF to just show wins
wins_2015_16 = year_2015_16[year_2015_16['WL'] == 'W']

#Find the teams overall wins
year_2015_16_total_wins = wins_2015_16.groupby('TEAM_NAME')['WL'].count().reset_index(name='Total_Wins')

In [428]:
team_2015_16_avg_pct['FG3A']= team_2015_16_avg_fga['FG3A']
team_2015_16_avg_pct['SEASON_YEAR'] = '2015-2016'
team_2015_16_avg_pct['Total_Wins']= year_2015_16_total_wins['Total_Wins']
team_2015_16_avg_pct

                 TEAM_NAME   FG3_PCT       FG3A SEASON_YEAR  Total_Wins
0            Atlanta Hawks  0.351646  28.365854   2015-2016          48
1           Boston Celtics  0.335305  26.121951   2015-2016          48
2            Brooklyn Nets  0.348439  18.390244   2015-2016          21
3        Charlotte Hornets  0.361549  29.390244   2015-2016          48
4            Chicago Bulls  0.368878  21.378049   2015-2016          42
5      Cleveland Cavaliers  0.362451  29.609756   2015-2016          57
6         Dallas Mavericks  0.343012  28.560976   2015-2016          42
7           Denver Nuggets  0.336829  23.695122   2015-2016          33
8          Detroit Pistons  0.343793  26.195122   2015-2016          44
9    Golden State Warriors  0.414232  31.609756   2015-2016          73
10         Houston Rockets  0.348061  30.890244   2015-2016          41
11          Indiana Pacers  0.348829  23.036585   2015-2016          45
12             LA Clippers  0.365171  26.707317   2015-2016          53
13      Los Angeles Lakers  0.317866  24.585366   2015-2016          17
14       Memphis Grizzlies  0.327683  18.548780   2015-2016          42
15              Miami Heat  0.333110  18.048780   2015-2016          48
16         Milwaukee Bucks  0.344866  15.573171   2015-2016          33
17  Minnesota Timberwolves  0.335512  16.426829   2015-2016          29
18    New Orleans Pelicans  0.357634  23.792683   2015-2016          30
19         New York Knicks  0.342963  21.487805   2015-2016          32
20   Oklahoma City Thunder  0.350000  23.719512   2015-2016          55
21           Orlando Magic  0.349756  22.170732   2015-2016          35
22      Philadelphia 76ers  0.337439  27.500000   2015-2016          10
23            Phoenix Suns  0.344366  25.829268   2015-2016          23
24  Portland Trail Blazers  0.368854  28.487805   2015-2016          44
25        Sacramento Kings  0.360293  22.426829   2015-2016          33
26       San Antonio Spurs  0.379695  18.512195   2015-2016          67
27         Toronto Raptors  0.366256  23.353659   2015-2016          56
28               Utah Jazz  0.356073  23.853659   2015-2016          40
29      Washington Wizards  0.358220  24.182927   2015-2016          41

In [136]:
#Filter year over year
year_2016_17 = regular_season_totals[regular_season_totals['SEASON_YEAR']=='2016-17']

#Find the overall 3p% per team for this year
team_2016_17_avg_pct = year_2016_17.groupby('TEAM_NAME')['FG3_PCT'].mean().reset_index()

#Find the average 3 points attempted by team
team_2016_17_avg_fga = year_2016_17.groupby('TEAM_NAME')['FG3A'].mean().reset_index()

#Find the years average FG3A 
year_2016_17_avg_fga = year_2016_17['FG3A'].mean()

#Find the years average FG3%
year_2016_17_avg_3perc = year_2016_17['FG3_PCT'].mean()

#Filter the DF to just show wins
wins_2016_17 = year_2016_17[year_2016_17['WL'] == 'W']

#Find the teams overall wins
year_2016_17_total_wins = wins_2016_17.groupby('TEAM_NAME')['WL'].count().reset_index(name='Total_Wins')

In [430]:
team_2016_17_avg_pct['FG3A']= team_2016_17_avg_fga['FG3A']
team_2016_17_avg_pct['SEASON_YEAR'] = '2016-2017'
team_2016_17_avg_pct['Total_Wins']= year_2016_17_total_wins['Total_Wins']
team_2016_17_avg_pct

                 TEAM_NAME   FG3_PCT       FG3A SEASON_YEAR  Total_Wins
0            Atlanta Hawks  0.341341  26.060976   2016-2017          43
1           Boston Celtics  0.358744  33.426829   2016-2017          53
2            Brooklyn Nets  0.337207  31.597561   2016-2017          20
3        Charlotte Hornets  0.348049  28.621951   2016-2017          36
4            Chicago Bulls  0.334402  22.329268   2016-2017          41
5      Cleveland Cavaliers  0.382171  33.890244   2016-2017          51
6         Dallas Mavericks  0.355366  30.158537   2016-2017          33
7           Denver Nuggets  0.368122  28.841463   2016-2017          40
8          Detroit Pistons  0.326878  23.353659   2016-2017          37
9    Golden State Warriors  0.385951  31.243902   2016-2017          67
10         Houston Rockets  0.356183  40.317073   2016-2017          55
11          Indiana Pacers  0.371537  22.987805   2016-2017          42
12             LA Clippers  0.373683  27.378049   2016-2017          51
13      Los Angeles Lakers  0.342500  25.731707   2016-2017          26
14       Memphis Grizzlies  0.350963  26.451220   2016-2017          43
15              Miami Heat  0.360902  26.987805   2016-2017          41
16         Milwaukee Bucks  0.372500  23.731707   2016-2017          42
17  Minnesota Timberwolves  0.346232  21.012195   2016-2017          31
18    New Orleans Pelicans  0.346659  26.780488   2016-2017          34
19         New York Knicks  0.348878  24.658537   2016-2017          31
20   Oklahoma City Thunder  0.326537  25.804878   2016-2017          47
21           Orlando Magic  0.328707  26.085366   2016-2017          29
22      Philadelphia 76ers  0.340024  29.792683   2016-2017          28
23            Phoenix Suns  0.333134  22.609756   2016-2017          24
24  Portland Trail Blazers  0.375098  27.707317   2016-2017          41
25        Sacramento Kings  0.380427  23.902439   2016-2017          32
26       San Antonio Spurs  0.394012  23.500000   2016-2017          61
27         Toronto Raptors  0.364927  24.341463   2016-2017          51
28               Utah Jazz  0.371610  25.951220   2016-2017          51
29      Washington Wizards  0.374037  24.756098   2016-2017          49

In [134]:
#Filter year over year
year_2017_18 = regular_season_totals[regular_season_totals['SEASON_YEAR']=='2017-18']

#Find the overall 3p% per team for this year
team_2017_18_avg_pct = year_2017_18.groupby('TEAM_NAME')['FG3_PCT'].mean().reset_index()

#Find the average 3 points attempted by team
team_2017_18_avg_fga = year_2017_18.groupby('TEAM_NAME')['FG3A'].mean().reset_index()

#Find the years average FG3A 
year_2017_18_avg_fga = year_2017_18['FG3A'].mean()

#Find the years average FG3%
year_2017_18_avg_3perc = year_2017_18['FG3_PCT'].mean()

#Filter the DF to just show wins
wins_2017_18 = year_2017_18[year_2017_18['WL'] == 'W']

#Find the teams overall wins
year_2017_18_total_wins = wins_2017_18.groupby('TEAM_NAME')['WL'].count().reset_index(name='Total_Wins')

In [432]:
team_2017_18_avg_pct['FG3A']= team_2017_18_avg_fga['FG3A']
team_2017_18_avg_pct['SEASON_YEAR'] = '2017-2018'
team_2017_18_avg_pct['Total_Wins']= year_2017_18_total_wins['Total_Wins']
team_2017_18_avg_pct

                 TEAM_NAME   FG3_PCT       FG3A SEASON_YEAR  Total_Wins
0            Atlanta Hawks  0.363463  31.024390   2017-2018          24
1           Boston Celtics  0.381280  30.390244   2017-2018          55
2            Brooklyn Nets  0.355890  35.658537   2017-2018          28
3        Charlotte Hornets  0.362878  27.231707   2017-2018          36
4            Chicago Bulls  0.353512  31.085366   2017-2018          27
5      Cleveland Cavaliers  0.372366  32.146341   2017-2018          50
6         Dallas Mavericks  0.360890  32.780488   2017-2018          24
7           Denver Nuggets  0.367207  30.926829   2017-2018          46
8          Detroit Pistons  0.372280  28.939024   2017-2018          39
9    Golden State Warriors  0.388805  28.890244   2017-2018          58
10         Houston Rockets  0.363829  42.317073   2017-2018          65
11          Indiana Pacers  0.365768  24.512195   2017-2018          48
12             LA Clippers  0.351159  26.780488   2017-2018          42
13      Los Angeles Lakers  0.339976  29.073171   2017-2018          35
14       Memphis Grizzlies  0.350988  26.243902   2017-2018          22
15              Miami Heat  0.357976  30.560976   2017-2018          44
16         Milwaukee Bucks  0.356268  24.682927   2017-2018          44
17  Minnesota Timberwolves  0.358000  22.500000   2017-2018          47
18    New Orleans Pelicans  0.359439  28.195122   2017-2018          48
19         New York Knicks  0.352585  23.341463   2017-2018          29
20   Oklahoma City Thunder  0.352146  30.378049   2017-2018          48
21           Orlando Magic  0.348012  29.329268   2017-2018          25
22      Philadelphia 76ers  0.366890  29.817073   2017-2018          52
23            Phoenix Suns  0.335378  27.878049   2017-2018          21
24  Portland Trail Blazers  0.367341  28.146341   2017-2018          49
25        Sacramento Kings  0.376915  23.987805   2017-2018          27
26       San Antonio Spurs  0.352256  24.109756   2017-2018          47
27         Toronto Raptors  0.357232  32.987805   2017-2018          59
28               Utah Jazz  0.366537  29.573171   2017-2018          48
29      Washington Wizards  0.372963  26.500000   2017-2018          43

In [132]:
#Filter year over year
year_2018_19 = regular_season_totals[regular_season_totals['SEASON_YEAR']=='2018-19']

#Find the overall 3p% per team for this year
team_2018_19_avg_pct = year_2018_19.groupby('TEAM_NAME')['FG3_PCT'].mean().reset_index()

#Find the average 3 points attempted by team
team_2018_19_avg_fga = year_2018_19.groupby('TEAM_NAME')['FG3A'].mean().reset_index()

#Find the years average FG3A 
year_2018_19_avg_fga = year_2018_19['FG3A'].mean()

#Find the years average FG3%
year_2018_19_avg_3perc = year_2018_19['FG3_PCT'].mean()

#Filter the DF to just show wins
wins_2018_19 = year_2018_19[year_2018_19['WL'] == 'W']

#Find the teams overall wins
year_2018_19_total_wins = wins_2018_19.groupby('TEAM_NAME')['WL'].count().reset_index(name='Total_Wins')

In [434]:
team_2018_19_avg_pct['FG3A']= team_2018_19_avg_fga['FG3A']
team_2018_19_avg_pct['SEASON_YEAR'] = '2018-2019'
team_2018_19_avg_pct['Total_Wins']= year_2018_19_total_wins['Total_Wins']
team_2018_19_avg_pct

                 TEAM_NAME   FG3_PCT       FG3A SEASON_YEAR  Total_Wins
0            Atlanta Hawks  0.350976  37.000000   2018-2019          29
1           Boston Celtics  0.363012  34.500000   2018-2019          49
2            Brooklyn Nets  0.352780  36.158537   2018-2019          42
3        Charlotte Hornets  0.351207  33.939024   2018-2019          39
4            Chicago Bulls  0.349183  25.890244   2018-2019          22
5      Cleveland Cavaliers  0.352024  29.121951   2018-2019          19
6         Dallas Mavericks  0.341451  36.609756   2018-2019          33
7           Denver Nuggets  0.349707  31.353659   2018-2019          54
8          Detroit Pistons  0.345780  34.804878   2018-2019          41
9    Golden State Warriors  0.384500  34.439024   2018-2019          57
10         Houston Rockets  0.353634  45.378049   2018-2019          53
11          Indiana Pacers  0.372366  25.378049   2018-2019          48
12             LA Clippers  0.387537  25.829268   2018-2019          48
13      Los Angeles Lakers  0.331171  30.987805   2018-2019          37
14       Memphis Grizzlies  0.339829  28.878049   2018-2019          33
15              Miami Heat  0.350573  32.414634   2018-2019          39
16         Milwaukee Bucks  0.353244  38.219512   2018-2019          60
17  Minnesota Timberwolves  0.355329  28.743902   2018-2019          36
18    New Orleans Pelicans  0.344073  29.865854   2018-2019          33
19         New York Knicks  0.339146  29.524390   2018-2019          17
20   Oklahoma City Thunder  0.351329  32.646341   2018-2019          49
21           Orlando Magic  0.356915  32.109756   2018-2019          42
22      Philadelphia 76ers  0.358939  30.170732   2018-2019          51
23            Phoenix Suns  0.327561  29.268293   2018-2019          19
24  Portland Trail Blazers  0.362110  30.731707   2018-2019          53
25        Sacramento Kings  0.376780  29.939024   2018-2019          39
26       San Antonio Spurs  0.396671  25.256098   2018-2019          48
27         Toronto Raptors  0.365183  33.792683   2018-2019          58
28               Utah Jazz  0.354500  34.012195   2018-2019          50
29      Washington Wizards  0.339195  33.304878   2018-2019          32

In [150]:
#Filter year over year
year_2019_20 = regular_season_totals[regular_season_totals['SEASON_YEAR']=='2019-20']

#Find the overall 3p% per team for this year
team_2019_20_avg_pct = year_2019_20.groupby('TEAM_NAME')['FG3_PCT'].mean().reset_index()

#Find the average 3 points attempted by team
team_2019_20_avg_fga = year_2019_20.groupby('TEAM_NAME')['FG3A'].mean().reset_index()

#Find the years average FG3A 
year_2019_20_avg_fga = year_2019_20['FG3A'].mean()

#Find the years average FG3%
year_2019_20_avg_3perc = year_2019_20['FG3_PCT'].mean()

#Filter the DF to just show wins
wins_2019_20 = year_2019_20[year_2019_20['WL'] == 'W']

#Find the teams overall wins
year_2019_20_total_wins = wins_2019_20.groupby('TEAM_NAME')['WL'].count().reset_index(name='Total_Wins')

In [436]:
team_2019_20_avg_pct['FG3A']= team_2019_20_avg_fga['FG3A']
team_2019_20_avg_pct['SEASON_YEAR'] = '2019-2020'
team_2019_20_avg_pct['Total_Wins']= year_2019_20_total_wins['Total_Wins']
team_2019_20_avg_pct

                 TEAM_NAME   FG3_PCT       FG3A SEASON_YEAR  Total_Wins
0            Atlanta Hawks  0.332448  36.059701   2019-2020          20
1           Boston Celtics  0.365847  34.541667   2019-2020          48
2            Brooklyn Nets  0.345097  38.138889   2019-2020          35
3        Charlotte Hornets  0.349277  34.323077   2019-2020          23
4            Chicago Bulls  0.347969  35.107692   2019-2020          22
5      Cleveland Cavaliers  0.347815  31.846154   2019-2020          19
6         Dallas Mavericks  0.366827  41.266667   2019-2020          43
7           Denver Nuggets  0.354945  30.602740   2019-2020          46
8          Detroit Pistons  0.368288  32.681818   2019-2020          20
9    Golden State Warriors  0.331754  31.261538   2019-2020          15
10         Houston Rockets  0.346375  45.291667   2019-2020          44
11          Indiana Pacers  0.362384  28.027397   2019-2020          45
12             LA Clippers  0.369444  33.472222   2019-2020          49
13      Los Angeles Lakers  0.347704  31.577465   2019-2020          52
14       Memphis Grizzlies  0.345247  31.465753   2019-2020          34
15              Miami Heat  0.380192  35.397260   2019-2020          44
16         Milwaukee Bucks  0.355342  38.904110   2019-2020          56
17  Minnesota Timberwolves  0.336500  39.687500   2019-2020          19
18    New Orleans Pelicans  0.369889  36.888889   2019-2020          30
19         New York Knicks  0.338273  28.363636   2019-2020          21
20   Oklahoma City Thunder  0.353889  30.152778   2019-2020          44
21           Orlando Magic  0.342466  32.246575   2019-2020          33
22      Philadelphia 76ers  0.366781  31.602740   2019-2020          43
23            Phoenix Suns  0.357548  31.780822   2019-2020          34
24  Portland Trail Blazers  0.374514  34.121622   2019-2020          35
25        Sacramento Kings  0.364556  34.875000   2019-2020          31
26       San Antonio Spurs  0.374549  28.464789   2019-2020          32
27         Toronto Raptors  0.376792  36.986111   2019-2020          53
28               Utah Jazz  0.375819  35.236111   2019-2020          44
29      Washington Wizards  0.368444  32.569444   2019-2020          25

In [152]:
#Filter year over year
year_2020_21 = regular_season_totals[regular_season_totals['SEASON_YEAR']=='2020-21']

#Find the overall 3p% per team for this year
team_2020_21_avg_pct = year_2020_21.groupby('TEAM_NAME')['FG3_PCT'].mean().reset_index()

#Find the average 3 points attempted by team
team_2020_21_avg_fga = year_2020_21.groupby('TEAM_NAME')['FG3A'].mean().reset_index()

#Find the years average FG3A 
year_2020_21_avg_fga = year_2020_21['FG3A'].mean()

#Find the years average FG3%
year_2020_21_avg_3perc = year_2020_21['FG3_PCT'].mean()

#Filter the DF to just show wins
wins_2020_21 = year_2020_21[year_2020_21['WL'] == 'W']

#Find the teams overall wins
year_2020_21_total_wins = wins_2020_21.groupby('TEAM_NAME')['WL'].count().reset_index(name='Total_Wins')

In [440]:
team_2020_21_avg_pct['FG3A']= team_2020_21_avg_fga['FG3A']
team_2020_21_avg_pct['SEASON_YEAR'] = '2020-2021'
team_2020_21_avg_pct['Total_Wins']= year_2020_21_total_wins['Total_Wins']
team_2020_21_avg_pct

                 TEAM_NAME   FG3_PCT       FG3A SEASON_YEAR  Total_Wins
0            Atlanta Hawks  0.370194  33.361111   2020-2021          41
1           Boston Celtics  0.375472  36.361111   2020-2021          36
2            Brooklyn Nets  0.389028  36.111111   2020-2021          48
3        Charlotte Hornets  0.367972  37.027778   2020-2021          33
4            Chicago Bulls  0.365528  33.972222   2020-2021          31
5      Cleveland Cavaliers  0.336778  29.736111   2020-2021          22
6         Dallas Mavericks  0.359556  38.111111   2020-2021          42
7           Denver Nuggets  0.377792  34.194444   2020-2021          47
8          Detroit Pistons  0.351500  32.916667   2020-2021          20
9    Golden State Warriors  0.374194  38.736111   2020-2021          39
10         Houston Rockets  0.338639  40.597222   2020-2021          17
11          Indiana Pacers  0.364694  33.958333   2020-2021          34
12             LA Clippers  0.412556  34.694444   2020-2021          47
13      Los Angeles Lakers  0.353431  31.222222   2020-2021          42
14       Memphis Grizzlies  0.354806  31.361111   2020-2021          38
15              Miami Heat  0.359111  36.194444   2020-2021          40
16         Milwaukee Bucks  0.385819  37.069444   2020-2021          46
17  Minnesota Timberwolves  0.349542  37.583333   2020-2021          23
18    New Orleans Pelicans  0.346903  30.416667   2020-2021          31
19         New York Knicks  0.391278  30.041667   2020-2021          41
20   Oklahoma City Thunder  0.339472  35.125000   2020-2021          22
21           Orlando Magic  0.339028  31.777778   2020-2021          21
22      Philadelphia 76ers  0.376000  30.125000   2020-2021          49
23            Phoenix Suns  0.377333  34.583333   2020-2021          51
24  Portland Trail Blazers  0.386056  40.819444   2020-2021          42
25        Sacramento Kings  0.363750  33.333333   2020-2021          31
26       San Antonio Spurs  0.346778  28.416667   2020-2021          33
27         Toronto Raptors  0.367611  39.319444   2020-2021          27
28               Utah Jazz  0.387778  43.027778   2020-2021          52
29      Washington Wizards  0.353139  29.000000   2020-2021          34

In [154]:
#Filter year over year
year_2021_22 = regular_season_totals[regular_season_totals['SEASON_YEAR']=='2021-22']

#Find the overall 3p% per team for this year
team_2021_22_avg_pct = year_2021_22.groupby('TEAM_NAME')['FG3_PCT'].mean().reset_index()

#Find the average 3 points attempted by team
team_2021_22_avg_fga = year_2021_22.groupby('TEAM_NAME')['FG3A'].mean().reset_index()

#Find the years average FG3A 
year_2021_22_avg_fga = year_2021_22['FG3A'].mean()

#Find the years average FG3%
year_2021_22_avg_3perc = year_2021_22['FG3_PCT'].mean()

#Filter the DF to just show wins
wins_2021_22 = year_2021_22[year_2021_22['WL'] == 'W']

#Find the teams overall wins
year_2021_22_total_wins = wins_2021_22.groupby('TEAM_NAME')['WL'].count().reset_index(name='Total_Wins')

In [442]:
team_2021_22_avg_pct['FG3A']= team_2021_22_avg_fga['FG3A']
team_2021_22_avg_pct['SEASON_YEAR'] = '2021-2022'
team_2021_22_avg_pct['Total_Wins']= year_2021_22_total_wins['Total_Wins']
team_2021_22_avg_pct

                 TEAM_NAME   FG3_PCT       FG3A SEASON_YEAR  Total_Wins
0            Atlanta Hawks  0.371744  34.402439   2021-2022          43
1           Boston Celtics  0.352439  37.121951   2021-2022          51
2            Brooklyn Nets  0.359646  31.731707   2021-2022          44
3        Charlotte Hornets  0.365207  38.170732   2021-2022          43
4            Chicago Bulls  0.366500  28.829268   2021-2022          46
5      Cleveland Cavaliers  0.352817  32.756098   2021-2022          44
6         Dallas Mavericks  0.351024  37.353659   2021-2022          52
7           Denver Nuggets  0.351549  35.902439   2021-2022          48
8          Detroit Pistons  0.327183  34.609756   2021-2022          23
9    Golden State Warriors  0.364524  39.402439   2021-2022          53
10         Houston Rockets  0.345854  38.658537   2021-2022          20
11          Indiana Pacers  0.344488  35.353659   2021-2022          25
12             LA Clippers  0.373037  34.170732   2021-2022          42
13      Los Angeles Lakers  0.346817  34.463415   2021-2022          33
14       Memphis Grizzlies  0.352671  32.670732   2021-2022          56
15              Miami Heat  0.378561  35.804878   2021-2022          53
16         Milwaukee Bucks  0.365634  38.426829   2021-2022          51
17  Minnesota Timberwolves  0.359329  41.292683   2021-2022          46
18    New Orleans Pelicans  0.335561  32.060976   2021-2022          36
19         New York Knicks  0.356683  36.939024   2021-2022          37
20   Oklahoma City Thunder  0.322878  37.390244   2021-2022          24
21           Orlando Magic  0.329805  36.853659   2021-2022          22
22      Philadelphia 76ers  0.363854  31.804878   2021-2022          51
23            Phoenix Suns  0.364378  31.902439   2021-2022          64
24  Portland Trail Blazers  0.342439  36.792683   2021-2022          27
25        Sacramento Kings  0.346268  33.195122   2021-2022          30
26       San Antonio Spurs  0.350598  32.024390   2021-2022          34
27         Toronto Raptors  0.349037  34.243902   2021-2022          48
28               Utah Jazz  0.359866  40.341463   2021-2022          49
29      Washington Wizards  0.342939  30.634146   2021-2022          35

In [156]:
#Filter year over year
year_2022_23 = regular_season_totals[regular_season_totals['SEASON_YEAR']=='2022-23']

#Find the overall 3p% per team for this year
team_2022_23_avg_pct = year_2022_23.groupby('TEAM_NAME')['FG3_PCT'].mean().reset_index()

#Find the average 3 points attempted by team
team_2022_23_avg_fga = year_2022_23.groupby('TEAM_NAME')['FG3A'].mean().reset_index()

#Find the years average FG3A 
year_2022_23_avg_fga = year_2022_23['FG3A'].mean()

#Find the years average FG3%
year_2022_23_avg_3perc = year_2022_23['FG3_PCT'].mean()

#Filter the DF to just show wins
wins_2022_23 = year_2022_23[year_2022_23['WL'] == 'W']

#Find the teams overall wins
year_2022_23_total_wins = wins_2022_23.groupby('TEAM_NAME')['WL'].count().reset_index(name='Total_Wins')

In [444]:
team_2022_23_avg_pct['FG3A']= team_2022_23_avg_fga['FG3A']
team_2022_23_avg_pct['SEASON_YEAR'] = '2022-2023'
team_2022_23_avg_pct['Total_Wins']= year_2022_23_total_wins['Total_Wins']
team_2022_23_avg_pct

                 TEAM_NAME   FG3_PCT       FG3A SEASON_YEAR  Total_Wins
0            Atlanta Hawks  0.353390  30.548780   2022-2023          41
1           Boston Celtics  0.375402  42.585366   2022-2023          57
2            Brooklyn Nets  0.380134  33.792683   2022-2023          45
3        Charlotte Hornets  0.329476  32.548780   2022-2023          27
4            Chicago Bulls  0.357000  28.865854   2022-2023          40
5      Cleveland Cavaliers  0.366317  31.573171   2022-2023          51
6         Dallas Mavericks  0.371317  41.000000   2022-2023          38
7           Denver Nuggets  0.376012  31.207317   2022-2023          53
8          Detroit Pistons  0.347878  32.426829   2022-2023          17
9    Golden State Warriors  0.384634  43.170732   2022-2023          44
10         Houston Rockets  0.323146  31.939024   2022-2023          22
11          Indiana Pacers  0.365951  36.951220   2022-2023          35
12             LA Clippers  0.377000  33.341463   2022-2023          44
13      Los Angeles Lakers  0.348037  31.195122   2022-2023          43
14       Memphis Grizzlies  0.349780  34.231707   2022-2023          51
15              Miami Heat  0.344317  34.780488   2022-2023          44
16         Milwaukee Bucks  0.367915  40.317073   2022-2023          58
17  Minnesota Timberwolves  0.363512  33.304878   2022-2023          42
18    New Orleans Pelicans  0.361561  30.097561   2022-2023          42
19         New York Knicks  0.353841  35.731707   2022-2023          47
20   Oklahoma City Thunder  0.356890  34.109756   2022-2023          40
21           Orlando Magic  0.348073  31.109756   2022-2023          34
22      Philadelphia 76ers  0.385012  32.621951   2022-2023          54
23            Phoenix Suns  0.371317  32.609756   2022-2023          45
24  Portland Trail Blazers  0.364146  35.280488   2022-2023          33
25        Sacramento Kings  0.367720  37.317073   2022-2023          48
26       San Antonio Spurs  0.346488  32.195122   2022-2023          22
27         Toronto Raptors  0.336159  32.024390   2022-2023          41
28               Utah Jazz  0.351988  37.792683   2022-2023          37
29      Washington Wizards  0.354232  31.719512   2022-2023          35

In [158]:
#Filter year over year
year_2023_24 = regular_season_totals[regular_season_totals['SEASON_YEAR']=='2023-24']

#Find the overall 3p% per team for this year
team_2023_24_avg_pct = year_2023_24.groupby('TEAM_NAME')['FG3_PCT'].mean().reset_index()

#Find the average 3 points attempted by team
team_2023_24_avg_fga = year_2023_24.groupby('TEAM_NAME')['FG3A'].mean().reset_index()

#Find the years average FG3A 
year_2023_24_avg_fga = year_2023_24['FG3A'].mean()

#Find the years average FG3%
year_2023_24_avg_3perc = year_2023_24['FG3_PCT'].mean()

#Filter the DF to just show wins
wins_2023_24 = year_2023_24[year_2023_24['WL'] == 'W']

#Find the teams overall wins
year_2023_24_total_wins = wins_2023_24.groupby('TEAM_NAME')['WL'].count().reset_index(name='Total_Wins')

In [446]:
team_2023_24_avg_pct['FG3A']= team_2023_24_avg_fga['FG3A']
team_2023_24_avg_pct['SEASON_YEAR'] = '2023-2024'
team_2023_24_avg_pct['Total_Wins']= year_2023_24_total_wins['Total_Wins']
team_2023_24_avg_pct

                 TEAM_NAME   FG3_PCT       FG3A SEASON_YEAR  Total_Wins
0            Atlanta Hawks  0.364159  37.707317   2023-2024          36
1           Boston Celtics  0.387598  42.463415   2023-2024          64
2            Brooklyn Nets  0.361817  36.707317   2023-2024          32
3        Charlotte Hornets  0.353366  34.000000   2023-2024          21
4            Chicago Bulls  0.356902  32.073171   2023-2024          39
5      Cleveland Cavaliers  0.366378  36.780488   2023-2024          48
6         Dallas Mavericks  0.367012  39.536585   2023-2024          50
7           Denver Nuggets  0.373268  31.219512   2023-2024          57
8          Detroit Pistons  0.348780  31.731707   2023-2024          14
9    Golden State Warriors  0.379061  38.914634   2023-2024          46
10         Houston Rockets  0.352061  36.146341   2023-2024          41
11          Indiana Pacers  0.372854  35.256098   2023-2024          47
12             LA Clippers  0.382427  33.158537   2023-2024          51
13      Los Angeles Lakers  0.374268  31.365854   2023-2024          47
14       Memphis Grizzlies  0.345232  37.768293   2023-2024          27
15              Miami Heat  0.370000  33.719512   2023-2024          46
16         Milwaukee Bucks  0.372683  38.073171   2023-2024          49
17  Minnesota Timberwolves  0.387012  32.695122   2023-2024          56
18    New Orleans Pelicans  0.378134  32.597561   2023-2024          49
19         New York Knicks  0.369463  35.804878   2023-2024          50
20   Oklahoma City Thunder  0.387207  34.207317   2023-2024          57
21           Orlando Magic  0.352232  31.317073   2023-2024          47
22      Philadelphia 76ers  0.360037  33.329268   2023-2024          47
23            Phoenix Suns  0.379866  32.573171   2023-2024          49
24  Portland Trail Blazers  0.345659  33.207317   2023-2024          21
25        Sacramento Kings  0.365598  39.256098   2023-2024          46
26       San Antonio Spurs  0.348805  36.378049   2023-2024          22
27         Toronto Raptors  0.345829  33.073171   2023-2024          25
28               Utah Jazz  0.353134  36.500000   2023-2024          31
29      Washington Wizards  0.347488  35.548780   2023-2024          15

In [452]:
#Export to CSV

team_2010_11_avg_pct.to_csv('team_2010_11_avg_pct.csv', index=False)
team_2011_12_avg_pct.to_csv('team_2011_12_avg_pct.csv', index=False)
team_2012_13_avg_pct.to_csv('team_2012_13_avg_pct.csv', index=False)
team_2013_14_avg_pct.to_csv('team_2013_14_avg_pct.csv', index=False)
team_2014_15_avg_pct.to_csv('team_2014_15_avg_pct.csv', index=False)
team_2015_16_avg_pct.to_csv('team_2015_16_avg_pct.csv', index=False)
team_2016_17_avg_pct.to_csv('team_2016_17_avg_pct.csv', index=False)
team_2017_18_avg_pct.to_csv('team_2017_18_avg_pct.csv', index=False)
team_2018_19_avg_pct.to_csv('team_2018_19_avg_pct.csv', index=False)
team_2019_20_avg_pct.to_csv('team_2019_20_avg_pct.csv', index=False)
team_2020_21_avg_pct.to_csv('team_2020_21_avg_pct.csv', index=False)
team_2021_22_avg_pct.to_csv('team_2021_22_avg_pct.csv', index=False)
team_2022_23_avg_pct.to_csv('team_2022_23_avg_pct.csv', index=False)
team_2023_24_avg_pct.to_csv('team_2023_24_avg_pct.csv', index=False)

In [300]:
#Find the overall fgA avg, overall 3P%avg and avg wins

#Find the overall 3p% per team for the total DF
overall_avg_pct = regular_season_totals.groupby('TEAM_NAME')['FG3_PCT'].mean().reset_index()

#Find the average 3 points attempted by team
overall_avg_fga = regular_season_totals.groupby('TEAM_NAME')['FG3A'].mean().reset_index()

#Find the years average FG3A 
overall_avg_fga = regular_season_totals['FG3A'].mean()

#Find the years average FG3%
overall_avg_3perc = regular_season_totals['FG3_PCT'].mean()

#Filter the DF to just show wins
overall_total_wins = regular_season_totals[regular_season_totals['WL'] == 'W']

overall_total_wins['Count'] = 1

#Find the teams overall wins
overalltotal_wins = overall_total_wins.groupby(['SEASON_YEAR', 'TEAM_NAME'])['WL'].count()

grand_avg_wins = overalltotal_wins.mean()

overall_total_wins = overall_total_wins.groupby(['SEASON_YEAR', 'TEAM_NAME'])['Count'].sum().reset_index()

# Calculate the team grand average wins
team_grand_avg_wins = overall_total_wins.groupby('TEAM_NAME')['Count'].mean()

C:\Users\jswin\AppData\Local\Temp\ipykernel_21260\1752070223.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  overall_total_wins['Count'] = 1

In [302]:
team_grand_avg_wins

TEAM_NAME
Atlanta Hawks             39.357143
Boston Celtics            47.285714
Brooklyn Nets             37.166667
Charlotte Bobcats         26.250000
Charlotte Hornets         33.900000
Chicago Bulls             40.357143
Cleveland Cavaliers       36.500000
Dallas Mavericks          42.142857
Denver Nuggets            45.357143
Detroit Pistons           28.571429
Golden State Warriors     48.285714
Houston Rockets           42.142857
Indiana Pacers            42.214286
LA Clippers               47.444444
Los Angeles Clippers      48.200000
Los Angeles Lakers        37.357143
Memphis Grizzlies         42.428571
Miami Heat                47.142857
Milwaukee Bucks           42.785714
Minnesota Timberwolves    32.785714
New Jersey Nets           23.000000
New Orleans Hornets       31.333333
New Orleans Pelicans      37.454545
New York Knicks           35.071429
Oklahoma City Thunder     46.571429
Orlando Magic             31.785714
Philadelphia 76ers        38.000000
Phoenix Suns              36.785714
Portland Trail Blazers    39.928571
Sacramento Kings          32.000000
San Antonio Spurs         46.571429
Toronto Raptors           42.428571
Utah Jazz                 41.642857
Washington Wizards        33.642857
Name: Count, dtype: float64

In [262]:
#Answering stretch question: Does higher 3pt% lead to more wins year over year

#Filter the total DF to just W
overall_w = regular_season_totals[regular_season_totals['WL']=='W']

#Filter by season year/team and 3p%
total_average_3Pperc = overall_w.groupby(['SEASON_YEAR', 'TEAM_NAME'])['FG3_PCT'].mean().reset_index(name='Total Average 3P%')

#Calculate total wins per year
total_wins_avg = overall_w.groupby(['SEASON_YEAR', 'TEAM_NAME'])['WL'].count().reset_index(name='Total_Wins')

#Merge the 2 new DF
season_stats = pd.merge(total_average_3Pperc, total_wins_avg, on=['SEASON_YEAR', 'TEAM_NAME'])